name:                coformat
version:             0.3.0.0
github:              "0xd34df00d/coformat"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generate clang-format config based on some existing code base
category:            Language

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/coformat#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- async-pool >= 0.9.1
- bytestring
- can-i-haz
- command
- command-qq >= 0.3.1.0
- containers
- dom-selector
- extra
- fast-logger
- filepath
- generic-data
- hashable
- html-conduit
- interpolate
- lens
- lens-aeson
- monad-logger
- mtl
- optparse-generic
- regex-applicative
- scientific
- template-haskell
- temporary
- text
- transformers
- unordered-containers
- xml-conduit
- yaml

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  coformat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coformat

tests:
  coformat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coformat
